### ISSUE TITLE
Bug: Instance Table no longer displays any data on a Survey page.

### ISSUE THREAD

**Issue by jgardner-qha** [lsgs/redcap-instance-table#35]
Prior to REDCap v13.4.11, instance tables on a Survey page would appear correctly. Since then (or v13.4.12, I'm not sure), the instance table on a survey page appears empty (no data). The same instance table on a data entry page appears as expected.

See https://redcap.vanderbilt.edu/community/post.php?id=204096 for additional details.

**Comment by jgardner-qha** [comment]
Correction... this doesn't appear to be a problem with a REDCap upgrade, it appears to have been introduced in redcap-instance-table v1.5.11.
[https://github.com/lsgs/redcap-instance-table/compare/1.5.10...1.5.11#diff-8ec4dc351c400ca7f6bd45a5b96cc0c8ee965be2e7f5489e9a2d70dda406cd28R394](url)

Commenting line 394 in InstanceTable.php seems to fix this problem.
`## if ($this->isSurvey) return array(); // ajax calls from surveys not allowed`

**Comment by steentje34** [comment]
We are experiencing the same issue with EM v1.5.11, REDCap v13.1.27 & PHP 7.4.30. @lsgs, please do not hesitate to contact me if you need more information.

**Comment by lsgs** [comment]
This is fixed in 1.5.12. THanks for the report @jgardner-qha

**Comment by ksultana102** [comment]
We are currently utilizing REDCap version 13.1.37 PHP 7.4.13 and have been using Instance Table - v1.5.11. To address the issue with the survey, we attempted to roll back to both v1.5.10 and v1.5.12, but unfortunately, the problem persisted. This issue seems to be limited to the survey, as it works perfectly fine on the data entry form. We also tested the latest version, v1.5.14, but it didn't resolve the problem.
